### ISSUE TITLE
Images bug

### ISSUE THREAD

**Issue by segunajibola** [segunajibola/nft-site#2]
fix images

**Comment by AbdelrahmanDwedar** [comment]
What is the images' problem exactly? 🤔

**Comment by segunajibola** [comment]
hey bro, i just fixed it myself.

**Comment by segunajibola** [comment]
check this for fixing https://github.com/segunajibola/surprise-gift/issues/1

**Comment by AbdelrahmanDwedar** [comment]
> hey bro, i just fixed it myself.

Oh, great



> check this for fixing [segunajibola/surprise-gift#1](https://github.com/segunajibola/surprise-gift/issues/1)

Sure!!
